version: '3'

services:
  openldap:
    image: osixia/openldap:latest
    ports:
      - 389:389
      - 636:636
    command: --loglevel debug
    environment:
      LDAP_ORGANISATION: Infi
      LDAP_DOMAIN: infi.nl
      LDAP_ADMIN_PASSWORD: IetsGeheims

    volumes:
    - "./db:/var/lib/ldap"
    - "./slapd.d:/etc/ldap/slapd.d"
